In [89]:
import numpy as np

**How to set a random seed for reproducibility?**

In [90]:
rnd1 =np.random.RandomState()
x1 = rnd1.uniform(low =5,high =10, size =(2,3)) #means values between 5 and 10 and the array has a shape of 2x3
x1 
#not reproducing the same value

array([[6.46884394, 6.26077866, 8.03494351],
       [8.51499591, 7.59191677, 7.61353595]])

In [91]:
rnd2 =np.random.RandomState(seed =1234)
x2 = rnd2.uniform(low =0.0,high =1.0, size =(2,3))
x2
#reproduces the same value 

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261]])

### **How to extract Rows and columns from an array?**

In [92]:
x2[0,:] # first row having index 0

array([0.19151945, 0.62210877, 0.43772774])

In [93]:
x2[1,:] # second row having index 1

array([0.78535858, 0.77997581, 0.27259261])

In [94]:
x2[:,0] # first column having index 0

array([0.19151945, 0.78535858])

In [95]:
x2[:,1] # second column having index 1

array([0.62210877, 0.77997581])

In [97]:
x2[:,2] # third column having index 2

array([0.43772774, 0.27259261])

### **How to transpose an array?**

In [98]:
x2

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261]])

In [103]:
x2.shape

(2, 3)

In [102]:
x3 = x2.T # transposing x2 and storing it as x3
x3

array([[0.19151945, 0.78535858],
       [0.62210877, 0.77997581],
       [0.43772774, 0.27259261]])

In [104]:
x3.shape

(3, 2)

### **How to create a row vector between specified values with equally spaced intervals?**

In [117]:
k1 = np.linspace(8,20,4) 
# 8 = lower limit; 20 = upper limit; 4 = number of elements in the array including the  lower and upper limit
k1

array([ 8., 12., 16., 20.])

In [118]:
k2 = np.linspace(5,250,15) 
# 5 = lower limit; 250 = upper limit; 15 = number of elements in the array including the  lower and upper limit
k2

array([  5. ,  22.5,  40. ,  57.5,  75. ,  92.5, 110. , 127.5, 145. ,
       162.5, 180. , 197.5, 215. , 232.5, 250. ])