# <font color=red>**NumPy - Introduction** </font>

> NumPy is a Python package. It stands for 'Numerical Python'.

### <font color=red>    **Operations using NumPy** <font/> 

Using NumPy, a developer can perform the following operations 
    
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra.<br>
    
NumPy has in-built functions for linear algebra and random number generation.


### <font color=red>    **Why NumPy ? - Examples** <font/> 

#### <font color=blue> **How to add two lists element by element?**<font/>

In [5]:
test1 =[34,23,44,39]
test2 =[42,36,41,42]
total =test1+test2
total

[34, 23, 44, 39, 42, 36, 41, 42]

**lists did not add element by element but instead concatenated (added back to back)**

In [9]:
# method to add element by element using basic python

total=[]
for x,y in zip(test1,test2):
    total.append((x+y))
    
total

[76, 59, 85, 81]

#### <font color=blue> **How quick is Numpy?**<font/>

In [50]:
u=list(range(1000000))


In [51]:
%timeit sum(u)

6.51 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
import numpy as np

In [53]:
u_arr =np.array(u)

In [54]:
 %timeit (np.sum(u_arr))

649 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
(6.51*10**-3)/(649*10**-6)

10.030816640986133

#### <font color=blue> **Getting to know Numpy**<font/>

> **Creation of NumPy array**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b =np.array([7,8,9,5])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b

array([7, 8, 9, 5])

> **Checking whether the given variable is a NumPy array**

In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

> **A given NumPy array can have only have elements that belong to one numerical type. How to check the numerical type of the given NumPy array?**

In [7]:
a.dtype

dtype('int64')

In [8]:
b.dtype

dtype('int64')

In [9]:
c=a/b
c

array([0.14285714, 0.25      , 0.33333333, 0.8       ])

In [10]:
c.dtype

dtype('float64')

> **A NumPy array is a multidimensional array. How to check the dimensions of a given NumPy array?**

In [11]:
a.ndim

1

In [12]:
b.ndim

1

In [13]:
c.ndim

1

> **A NumPy array is a multidimensional array. How to check the length of each dimensions of a given NumPy array?**

In [14]:
a.shape

(4,)

In [15]:
p= np.array([[1],[9],[4],[7]])

In [16]:
p

array([[1],
       [9],
       [4],
       [7]])

In [17]:
p.shape

(4, 1)

In [18]:
k1 =np.array([[1,2,3],[3,4,7]])

In [19]:
k1

array([[1, 2, 3],
       [3, 4, 7]])

In [20]:
k1.shape

(2, 3)

In [21]:
k2 =np.array([[[1,2,3],[3,4,7]],[[7,8,6],[9,5,9]]])

In [22]:
k2

array([[[1, 2, 3],
        [3, 4, 7]],

       [[7, 8, 6],
        [9, 5, 9]]])

In [23]:
k2.shape

(2, 2, 3)

#### <font color=blue> **What is meant by broadcasting in NumPy?**<font/>

> **Any mathematical operations we perform to the array as a whole will be done to every element in that array. This is known as broadcasting in Numpy.**

In [24]:
a

array([1, 2, 3, 4])

In [25]:
a*10

array([10, 20, 30, 40])

In [26]:
b

array([7, 8, 9, 5])

In [27]:
a*b

array([ 7, 16, 27, 20])

#### <font color=blue> **Are the various common functions in` NumPy, python functions?**<font/>

>**No. They generally belong to a class called universal functions, written as ufunc.**

In [28]:
np.sin


<ufunc 'sin'>

In [29]:
np.log

<ufunc 'log'>

#### <font color=blue> **"NumPy arrays are mutable." What does it mean?**<font/>

>**It means you can pick any element or set any element to a value in NumPy arrays**

In [30]:
a

array([1, 2, 3, 4])

In [31]:
a[0] #picking the element at the 0th index

1

In [32]:
a[3]

4

In [33]:
a[0]=100 #setting the element at the 0th index with another value

In [34]:
a

array([100,   2,   3,   4])

In [35]:
a[2]=57

In [36]:
a

array([100,   2,  57,   4])

#### <font color=blue> **What is "type coercion" in NumPy arrays?**<font/>

>**It means, when you set a value which is not the same data type as the given array, it will force that input into that data type. This becomes an issue when you set a float value to a NumPy array which has a datatype of int**

In [37]:
a

array([100,   2,  57,   4])

In [38]:
a[0]=5.8

In [39]:
a

array([ 5,  2, 57,  4])

In [40]:
d=np.array([1.5,8.9,5.6,7.4])

In [41]:
d

array([1.5, 8.9, 5.6, 7.4])

In [42]:
d[2]=67

In [43]:
d

array([ 1.5,  8.9, 67. ,  7.4])

#### <font color=blue> **Can we specify the dtype in NumPy arrays?**<font/>

>**Yes we can. While constructing an array, we have an argument "dtype" by which we can force a dtype for that array being created. If it is not the default dtype it will be displayed**

In [44]:
f=np.array([1,2,3,4.6],dtype='int64')


In [45]:
f

array([1, 2, 3, 4])

In [46]:
h=np.array([1,2,3,4.6],dtype='float64')

In [47]:
h

array([1. , 2. , 3. , 4.6])

In [48]:
i=np.array([1,2,3,4.6],dtype='int32')

In [49]:
i

array([1, 2, 3, 4], dtype=int32)

#### <font color=blue> **How to pick any element or set any element to a value in a multidimensional NumPy array?**<font/>

>**by mentioning all the positions within a single square bracket**

In [50]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
d.shape 

(2, 3)

In [52]:
d[0,0] 

1

In [53]:
d[1,2] #index position 1 is second row, index position 2 is 3rd column

6

In [54]:
d[0,1]

2

In [55]:
d[1,2]=1000

In [56]:
d

array([[   1,    2,    3],
       [   4,    5, 1000]])

In [57]:
d[0,0]=678

In [58]:
d

array([[ 678,    2,    3],
       [   4,    5, 1000]])

#### <font color=blue> **How to slice a NumPy array?**<font/>

>**by same method as a list for python if the array is 1 dimensional**

In [59]:
a

array([ 5,  2, 57,  4])

In [60]:
a[1:3] # number of elements you will get = upper bound -lower bound

array([ 2, 57])

In [61]:
a[:-1]

array([ 5,  2, 57])

In [62]:
a[:3] # equivalent to [0:3]

array([ 5,  2, 57])

#### <font color=blue> **Three dimensional indexing of NumPy array**<font/>

In [63]:
q =np.array([[[1,2,3],[15,4,7]],[[16,8,6],[19,5,9]]])

In [64]:
q

array([[[ 1,  2,  3],
        [15,  4,  7]],

       [[16,  8,  6],
        [19,  5,  9]]])

In [65]:
q.shape

(2, 2, 3)

In [66]:
q[0,0,0] 

1

**first zero = [[1,2,3],[15,4,7]] selected; second zero = [1,2,3] selected; third zero = 1**

In [67]:
q[1,0,0] 

16

**first 1 = [[16,8,6],[19,5,9]] selected; second zero = [16,8,6] selected; third zero = 16**

In [68]:
q[0,1,0]

15

**first 0 = [[1,2,3],[15,4,7]] selected; second 1 =[15,4,7] selected; third zero = 15**

In [69]:
q[0,1,1]

4

**first 0 = [[1,2,3],[15,4,7]] selected; second 1 =[15,4,7] selected; third 1 = 4**

In [70]:
q[1,0,2]

6

**first 1 = [[16,8,6],[19,5,9]] selected; second zero = [16,8,6] selected; third 2 = 6**

#### <font color=blue> **Three dimensional slicing of NumPy array**<font/>

In [71]:
q

array([[[ 1,  2,  3],
        [15,  4,  7]],

       [[16,  8,  6],
        [19,  5,  9]]])

**I want the slice [4,7]. How can I get that?**

In [73]:
q[0,1,1:]

array([4, 7])

**I want the slice [16,8]. How can I get that?**

In [74]:
q[1,0,:2]

array([16,  8])

In [75]:
y=np.arange(25).reshape(5,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**I need the following from the above array:**
    
1) array([[ 1],
       [ 6],
       [11],
       [16],
       [21]]) (the second column)

2) array([[ 3],
       [ 8],
       [13],
       [18],
       [23]]) (the 4th column)
       
3) array([20, 21, 22, 23, 24]) (the last row)

3) array([[ 5,  7],
       [15, 17]])

**How can I get these?**

In [76]:
y.shape

(5, 5)

In [82]:
y[:,1:2] 
# first colon includes all rows, to get the elements of 2nd column i slice between index position 1 and 2

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [83]:
y[:,3:4]
# first colon includes all rows, to get the elements of 2nd column i slice between index position 3 and 4

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [84]:
y[4,:]
# I need last row, index 4, and all the columns

array([20, 21, 22, 23, 24])

In [81]:
y[1::2,:3:2]
# here we use stride of two. starting with second row (index 1) then skip 1 (stride of two)
# similarly, we start with first column upto the 3rd column skiping a column by using stride of two

array([[ 5,  7],
       [15, 17]])