# <font color=red>    **NumPy - Introduction** <font/>

> NumPy is a Python package. It stands for 'Numerical Python'.

### <font color=red>    **Operations using NumPy** <font/> 

Using NumPy, a developer can perform the following operations 
    
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra.<br>
    
NumPy has in-built functions for linear algebra and random number generation.


### <font color=red>    **Why NumPy ? - Examples** <font/> 

#### <font color=blue> **How to add two lists element by element?**<font/>

In [5]:
test1 =[34,23,44,39]
test2 =[42,36,41,42]
total =test1+test2
total

[34, 23, 44, 39, 42, 36, 41, 42]

**lists did not add element by element but instead concatenated (added back to back)**

In [9]:
# method to add element by element using basic python

total=[]
for x,y in zip(test1,test2):
    total.append((x+y))
    
total

[76, 59, 85, 81]

#### <font color=blue> **How quick is Numpy?**<font/>

In [50]:
u=list(range(1000000))


In [51]:
%timeit sum(u)

6.51 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
import numpy as np

In [53]:
u_arr =np.array(u)

In [54]:
 %timeit (np.sum(u_arr))

649 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
(6.51*10**-3)/(649*10**-6)

10.030816640986133

#### <font color=blue> **Getting to know Numpy**<font/>

> **Creation of NumPy array**

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b =np.array([7,8,9,5])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b

array([7, 8, 9, 5])

> **Checking whether the given variable is a NumPy array**

In [5]:
type(a)

numpy.ndarray

In [6]:
type(b)

numpy.ndarray

> **A given NumPy array can have only have elements that belong to one numerical type. How to check the numerical type of the given NumPy array?**

In [7]:
a.dtype

dtype('int64')

In [8]:
b.dtype

dtype('int64')

In [9]:
c=a/b
c

array([0.14285714, 0.25      , 0.33333333, 0.8       ])

In [10]:
c.dtype

dtype('float64')

> **A NumPy array is a multidimensional array. How to check the dimensions of a given NumPy array?**

In [11]:
a.ndim

1

In [12]:
b.ndim

1

In [13]:
c.ndim

1

> **A NumPy array is a multidimensional array. How to check the length of each dimensions of a given NumPy array?**

In [14]:
a.shape

(4,)

In [24]:
k1 =np.array([[1,2,3],[3,4,7]])

In [28]:
k1

array([[1, 2, 3],
       [3, 4, 7]])

In [25]:
k1.shape

(2, 3)

In [26]:
k2 =np.array([[[1,2,3],[3,4,7]],[[7,8,6],[9,5,9]]])

In [27]:
k2

array([[[1, 2, 3],
        [3, 4, 7]],

       [[7, 8, 6],
        [9, 5, 9]]])

In [21]:
k.shape

(2, 2, 3)