# <font color=red>    **NumPy - Introduction** <font/>

> NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects. Arrays are data structures that store information in a set of adjacent memory addresses.  

> In practice, this means is that you can store other variables and objects inside an array and can retrieve them from the array by referring to their position number in the array. NumPy also provides ways to process these arrays.


### <font color=red>    **Operations using NumPy** <font/> 

Using NumPy, a developer can perform the following operations 
    
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra.<br>
    
NumPy has in-built functions for linear algebra and random number generation.


### <font color=red>    **Why NumPy ? - An example** <font/> 

In [5]:
num =[2,4,6,8]

In [9]:
num

[2, 4, 6, 8]

In [6]:
import numpy as np

In [7]:
num_arr =np.array(num)

In [8]:
num_arr

array([2, 4, 6, 8])

In [10]:
num_half =num/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [11]:
num_arr_half =num_arr/2

In [12]:
num_arr_half

array([1., 2., 3., 4.])

In [13]:
num_arr2 =num_arr-1

In [14]:
num_arr2

array([1, 3, 5, 7])

In [15]:
num2 =num-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [16]:
age =[32,45,12,55]

In [17]:
age_arr =np.array(age)

In [18]:
year_of_birth =2020-age

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [19]:
year_of_birth =2020-age_arr

In [20]:
year_of_birth

array([1988, 1975, 2008, 1965])

In [24]:
x=[]
for i in age:
    y=2020-i
    x.append(y)
    
x

    

[1988, 1975, 2008, 1965]

In [26]:
s

[45]