# <font color=red>    **NumPy - Introduction** <font/>

> NumPy is a Python package. It stands for 'Numerical Python'.

### <font color=red>    **Operations using NumPy** <font/> 

Using NumPy, a developer can perform the following operations 
    
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra.<br>
    
NumPy has in-built functions for linear algebra and random number generation.


### <font color=red>    **Why NumPy ? - Examples** <font/> 

#### <font color=blue> **How to add two lists element by element?**<font/>

In [5]:
test1 =[34,23,44,39]
test2 =[42,36,41,42]
total =test1+test2
total

[34, 23, 44, 39, 42, 36, 41, 42]

**lists did not add element by element but instead concatenated (added back to back)**

In [9]:
# method to add element by element using basic python

total=[]
for x,y in zip(test1,test2):
    total.append((x+y))
    
total

[76, 59, 85, 81]

#### <font color=blue> **How quick is Numpy?**<font/>

In [50]:
u=list(range(1000000))


In [51]:
%timeit sum(u)

6.51 ms ± 247 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [52]:
import numpy as np

In [53]:
u_arr =np.array(u)

In [54]:
 %timeit (np.sum(u_arr))

649 µs ± 3.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [55]:
(6.51*10**-3)/(649*10**-6)

10.030816640986133

#### <font color=blue> **Getting to know Numpy**<font/>

> **Creation of NumPy array**

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b =np.array([7,8,9,5])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b

array([7, 8, 9, 5])

> **Checking whether the given variable is a NumPy array**

In [6]:
type(a)

numpy.ndarray

In [7]:
type(b)

numpy.ndarray

> **A given NumPy array can have only have elements that belong to one numerical type. How to check the numerical type of the given NumPy array?**

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('int64')

In [10]:
c=a/b
c

array([0.14285714, 0.25      , 0.33333333, 0.8       ])

In [11]:
c.dtype

dtype('float64')

> **A NumPy array is a multidimensional array. How to check the dimensions of a given NumPy array?**

In [12]:
a.ndim

1

In [13]:
b.ndim

1

In [14]:
c.ndim

1

> **A NumPy array is a multidimensional array. How to check the length of each dimensions of a given NumPy array?**

In [15]:
a.shape

(4,)

In [32]:
p= np.array([[1],[9],[4],[7]])

In [33]:
p

array([[1],
       [9],
       [4],
       [7]])

In [34]:
p.shape

(4, 1)

In [17]:
k1 =np.array([[1,2,3],[3,4,7]])

In [18]:
k1

array([[1, 2, 3],
       [3, 4, 7]])

In [19]:
k1.shape

(2, 3)

In [20]:
k2 =np.array([[[1,2,3],[3,4,7]],[[7,8,6],[9,5,9]]])

In [21]:
k2

array([[[1, 2, 3],
        [3, 4, 7]],

       [[7, 8, 6],
        [9, 5, 9]]])

In [35]:
k2.shape

(2, 2, 3)

#### <font color=blue> **What is meant by broadcasting in NumPy?**<font/>

> **Any mathematical operations we perform to the array as a whole will be done to every element in that array. This is known as broadcasting in Numpy.**

In [36]:
a

array([1, 2, 3, 4])

In [37]:
a*10

array([10, 20, 30, 40])

In [38]:
b

array([7, 8, 9, 5])

In [39]:
a*b

array([ 7, 16, 27, 20])

#### <font color=blue> **Are the various common functions in` NumPy, python functions?**<font/>

>**No. They generally belong to a class called universal functions, written as ufunc.**

In [56]:
np.sin


<ufunc 'sin'>

In [55]:
np.log

<ufunc 'log'>

In [40]:
np.sin(a) #takes angle in radians 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [51]:
np.sin(np.pi/2)

1.0

In [45]:
np.pi

3.141592653589793